from _typeshed import Incomplete

DEFAULT_CONNECTION_NAME: str
DEFAULT_DATABASE_NAME: str

class ConnectionFailure(Exception): ...

def register_connection(alias, db: Incomplete | None = ..., name: Incomplete | None = ..., host: Incomplete | None = ..., port: Incomplete | None = ..., read_preference=..., username: Incomplete | None = ..., password: Incomplete | None = ..., authentication_source: Incomplete | None = ..., authentication_mechanism: Incomplete | None = ..., authmechanismproperties: Incomplete | None = ..., **kwargs) -> None: ...
def disconnect(alias=...) -> None: ...
def disconnect_all() -> None: ...
def get_connection(alias=..., reconnect: bool = ...): ...
def get_db(alias=..., reconnect: bool = ...): ...
def connect(db: Incomplete | None = ..., alias=..., **kwargs): ...
